#!/usr/bin/env node
/**
 * workspace — create and maintain a Workspace Mode workspace.
 *
 *   node <team>/scripts/workspace.mjs init --project <path> [--workspace <dir>] [--dry-run]
 *   node <team>/scripts/workspace.mjs update [--workspace <dir>]
 *   node <team>/scripts/workspace.mjs doctor [--workspace <dir>]
 *
 * A workspace keeps three things apart: the team (this framework, the authoritative source), the
 * project (the git repository being engineered) and the task state. `init` writes
 *
 *   WORKSPACE.json      team_root, project_root, task_request, state_root (paths relative to the workspace)
 *   CLAUDE.md           loads the team for a Claude Code session opened in the workspace root
 *   .claude/            the RUNTIME: agents, rules, skills, hooks, tools and templates copied from the
 *                       team, with hashes in .claude/engineering-team.manifest.json. Generated: edit
 *                       the team source and run `update`, never these copies (preflight reports drift).
 *   TASK_REQUEST.md     the request template, if there is none yet
 *   .engineering/       task state
 *
 * The runtime is copied, not referenced, because Claude Code discovers agents, skills, rules and
 * hooks only under the session's own `.claude/`. It never writes into the project or the team,
 * never deletes, and never overwrites a file it did not install (conflicts are reported).
 * `update` refreshes runtime files that were not edited locally; `doctor` runs the preflight.
 * Exit: 0 ok · 1 conflicts or preflight errors · 2 usage error.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { isAbsolute, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { CONFIG_FILE, CONFIG_VERSION, IMPORT_LINE, loadContext, preflight } from '../.claude/tools/context.mjs';
import { parseArgs, samePath } from '../.claude/tools/lib.mjs';
import { install } from './install.mjs';

const FRAMEWORK = fileURLToPath(new URL('..', import.meta.url));

/** A path as written in WORKSPACE.json: relative to the workspace (POSIX), or absolute across drives. */
function configPath(workspace, p) {
  const rel = relative(workspace, p);
  if (isAbsolute(rel)) return p;
  const posix = rel.split(sep).join('/');
  return posix.startsWith('..') ? posix : `./${posix || '.'}`;
}

export function workspaceClaudeMd() {
  return `# Engineering Workspace

<!--
Generated by the AI Technical Team (scripts/workspace.mjs). This is a Workspace Mode workspace:
WORKSPACE.json names the team (the framework source), the project (the repository the team
engineers) and where task state lives. The team's operating contract is imported below from the
generated runtime in .claude/ — to change the team, edit the team source and run
\`node <team_root>/scripts/workspace.mjs update\`. Project-specific notes may be added above the import.
-->

This session is the Engineering Lead of an AI Technical Team working in **Workspace Mode**.
Read \`WORKSPACE.json\` for the roots. Engineering work happens in \`project_root\`; the team root is
read-only. To run a task: \`node .claude/tools/task.mjs start --type <TYPE>\`, then follow the
engineering-task skill.

${IMPORT_LINE}
`;
}

export function init({ project, workspace = process.cwd(), team = FRAMEWORK, request = 'TASK_REQUEST.md', state = '.engineering', dryRun = false } = {}) {
  if (!project) throw new Error('--project <path> is required: the git repository the team will engineer');
  const ws = resolve(workspace);
  const projectRoot = resolve(ws, project);
  const teamRoot = resolve(team);
  if (!existsSync(projectRoot)) throw new Error(`project ${projectRoot} does not exist`);
  if (samePath(teamRoot, projectRoot)) throw new Error('the project cannot be the team itself');
  const report = { created: [], updated: [], unchanged: [], conflicts: [], notes: [] };

  const config = {
    $comment: 'Workspace Mode. Paths are relative to this file. team_root: the AI Technical Team (read-only during tasks). project_root: the git repository the team engineers. task_request: the human\'s request. state_root: task records and cached context.',
    version: CONFIG_VERSION,
    team_root: configPath(ws, teamRoot),
    project_root: configPath(ws, projectRoot),
    task_request: configPath(ws, resolve(ws, request)),
    state_root: configPath(ws, resolve(ws, state)),
  };
  const configFile = join(ws, CONFIG_FILE);
  const write = (file, text) => { if (!dryRun) { mkdirSync(resolve(file, '..'), { recursive: true }); writeFileSync(file, text); } };
  if (existsSync(configFile)) {
    let existing = null;
    try { existing = JSON.parse(readFileSync(configFile, 'utf8')); } catch { /* reported below */ }
    const same = existing && ['team_root', 'project_root', 'task_request', 'state_root'].every((k) => existing[k] && samePath(resolve(ws, existing[k]), resolve(ws, config[k])));
    if (same) report.unchanged.push(CONFIG_FILE);
    else report.conflicts.push(`${CONFIG_FILE} — already exists with different roots; left untouched (edit it by hand, or use another workspace directory)`);
  } else {
    write(configFile, `${JSON.stringify(config, null, 2)}\n`);
    report.created.push(CONFIG_FILE);
  }
  if (report.conflicts.length) return report;

  const claudeFile = join(ws, 'CLAUDE.md');
  if (!existsSync(claudeFile)) { write(claudeFile, workspaceClaudeMd()); report.created.push('CLAUDE.md (workspace; imports the team)'); }

  const r = install(ws, { dryRun, framework: teamRoot, gitignore: false, workspace: true });
  report.created.push(...r.created.filter((f) => !f.startsWith('CLAUDE.md')));
  report.updated.push(...r.updated);
  report.unchanged.push(...r.unchanged);
  report.conflicts.push(...r.conflicts);

  const requestFile = resolve(ws, request);
  if (!existsSync(requestFile)) {
    write(requestFile, readFileSync(join(teamRoot, 'templates', 'TASK_REQUEST.md'), 'utf8'));
    report.created.push(`${configPath(ws, requestFile).replace(/^\.\//, '')} (template: fill in TASK and GOAL)`);
  }
  if (!dryRun) mkdirSync(join(resolve(ws, state), 'tasks'), { recursive: true });

  if (!dryRun) {
    const pre = preflight(loadContext({ root: ws }), { request: false });
    report.preflight = pre;
  }
  report.notes.push(
    'Next: write the task in TASK_REQUEST.md, open Claude Code in the workspace root, and say:',
    '  Start the engineering team and execute TASK_REQUEST.md through verified completion.',
    'The runtime in .claude/ is generated from the team: change the team source, then run `update`.',
  );
  return report;
}

export function update({ workspace = process.cwd(), dryRun = false } = {}) {
  const ctx = loadContext({ root: resolve(workspace) });
  if (ctx.mode !== 'workspace') throw new Error(`${resolve(workspace)} has no ${CONFIG_FILE}: run \`init\` first`);
  const r = install(ctx.workspace_root, { dryRun, update: true, framework: ctx.team_root, gitignore: false, workspace: true });
  if (r.conflicts.length) r.notes.push('Conflicting runtime files were edited in the workspace. Move those edits into the team source (the authoritative copy), then delete the workspace copy and re-run update.');
  if (!dryRun) r.preflight = preflight(ctx, { request: false });
  return r;
}

function main() {
  const [cmd, ...rest] = process.argv.slice(2);
  let opts;
  try { opts = parseArgs(rest, { booleans: ['dry-run'] }); } catch (err) { process.stderr.write(`workspace: ${err.message}\n`); process.exit(2); }
  const print = (r) => {
    const section = (name, items) => items.length && process.stdout.write(`${name} (${items.length}):\n${items.map((x) => `  ${x}`).join('\n')}\n`);
    if (opts['dry-run']) process.stdout.write('DRY RUN — nothing written\n');
    section('Created', r.created); section('Updated', r.updated); section('Conflicts', r.conflicts);
    process.stdout.write(`Unchanged: ${r.unchanged.length}\n`);
    if (r.preflight) {
      for (const w of r.preflight.warnings) process.stdout.write(`warning: ${w}\n`);
      process.stdout.write(r.preflight.errors.length ? `preflight: FAILED\n${r.preflight.errors.map((e) => `  - ${e}`).join('\n')}\n` : 'preflight: OK\n');
    }
    process.stdout.write(`${r.notes.join('\n')}\n`);
    if (r.conflicts.length || r.preflight?.errors.length) process.exitCode = 1;
  };
  try {
    if (cmd === 'init') print(init({ project: opts.project, workspace: opts.workspace, request: opts.request, state: opts.state, dryRun: opts['dry-run'] }));
    else if (cmd === 'update') print(update({ workspace: opts.workspace, dryRun: opts['dry-run'] }));
    else if (cmd === 'doctor') {
      const ctx = loadContext({ root: resolve(opts.workspace ?? process.cwd()) });
      if (ctx.mode !== 'workspace') throw new Error(`no ${CONFIG_FILE} here: run \`init\` first`);
      const pre = preflight(ctx);
      for (const w of pre.warnings) process.stdout.write(`warning: ${w}\n`);
      process.stdout.write(pre.errors.length ? `preflight: FAILED\n${pre.errors.map((e) => `  - ${e}`).join('\n')}\n` : 'preflight: OK\n');
      if (pre.errors.length) process.exitCode = 1;
    } else {
      process.stderr.write('usage: workspace.mjs init --project <path> [--workspace <dir>] [--dry-run] | update [--workspace <dir>] | doctor [--workspace <dir>]\n');
      process.exitCode = 2;
    }
  } catch (err) {
    process.stderr.write(`workspace: ${err.message}\n`);
    process.exitCode = 2;
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main();
